---
- name: check connection to engine 
  become: true
  hosts: localhost
  gather_facts: false
  vars_files:
    - ovirt_auth_vars.yml
    - stand.yml
  vars:
    vm_name: b12
    vm_type: server
    vm_os: other_linux

  tasks:
    - name: Login
      ansible.builtin.include_role:
        name: ovirt_login



    - name: Logout from oVirt
      ansible.builtin.include_role:
        name: ovirt_logout



auth: "{{ ovirt_auth }}"

    - name: Remove vm after finish
      ansible.builtin.include_role:
        name: remove_vm

    - name: Remove vm after finish
      ansible.builtin.include_role:
        name: create_vm_alma_temp_and_dont_run