---
- name: check connection to engine 
  become: true
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Login
      ovirt_auth:
        url: "https://ps-eng40-engine.ps.local/ovirt-engine/api"
        username: "admin@internal"
        password: "SuperSecretPassword"

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      when: not loggedin.skipped | default(false)