---
- name: check connection to engine 
  become: true
  hosts: localhost
  gather_facts: false
  vars_files:
    - ovirt_auth_vars.yml
    - stand.yml
  vars:
    vm_name: b04
    vm_type: server
    vm_os: Linux
  tasks:
    - name: Login
      ansible.builtin.include_role:
        name: ovirt_login

    - ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_name }}_thin_disk"
        size: 1GiB
        format: cow
        interface: virtio
        storage_domain: "{{ storage_nfs }}"
    - ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"        
        state: present
        cluster: "{{ vm_cluster_default }}"
        name: "{{ vm_name }}"
        memory: 2GiB
        cpu_cores: 2
        cpu_sockets: 2
        cpu_shares: 1024
        type: "{{ vm_type }}"
        high_availability: true
        operating_system: "{{ vm_os }}"
        disks:
          - name: "{{ vm_name }}_thin_disk"
            bootable: True
        nics:
          - name: nic1
    - name: Remove VM, if VM is running it will be stopped
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"      
        state: absent
        name: "{{ vm_name }}"

    - name: Logout from oVirt
      ansible.builtin.include_role:
        name: ovirt_logout