---
- name: check connection to engine 
  become: true
  hosts: localhost
  gather_facts: false
  vars_files:
    - ovirt_auth_vars.yml
  vars:
    vm_name: b04
    storage_domain: NFS
    vm_type: server
    vm_os: Linux
  tasks:
    - name: Login
      ovirt_auth:
        url: "{{ url }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: loggedin

    - ovirt.ovirt.ovirt_disk:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm_name }}_thin_disk"
        size: 1GiB
        format: cow
        interface: virtio
        storage_domain: NFS
    - ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"        
        state: present
        cluster: Default
        name: "{{ vm_name }}"
        memory: 2GiB
        cpu_cores: 2
        cpu_sockets: 2
        cpu_shares: 1024
        type: "{{ vm_type }}"
        high_availability: true
        operating_system: "{{ vm_os }}"
        disks:
          - name: "{{ vm_name }}_thin_disk"
            bootable: True
        nics:
          - name: nic1
    - name: Remove VM, if VM is running it will be stopped
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"      
        state: absent
        name: "{{ vm_name }}"

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      when: not loggedin.skipped | default(false)