---
- name: check connection to engine 
  become: true
  hosts: localhost
  gather_facts: false
  vars_files:
    - ovirt_auth_vars.yml
  vars:
    vm_name: b06
    vm_storage_domain: NFS
    vm_type: server
    vm_os: Linux
    vm_cluster: Default
  tasks:
    - name: Login
      ansible.builtin.include_role:
        name: ovirt_login
      register: loggedin
    - ansible.builtin.include_role:
        name: create_thin_disk
    - ansible.builtin.include_role:
        name: create_linux_vm

    - name: Import external ova VM
      ovirt.ovirt.ovirt_vm:
        cluster: "{{ vm_cluster }}"
        name: "{{ vm_name }}"
        host: myhost
        timeout: 1800
        poll_interval: 30
        kvm:
          name: "{{ vm_name }}"
          url: ova:///path/myvm.ova
          storage_domain: "{{ vm_storage_domain }}"


    - name: Logout from oVirt
      ansible.builtin.include_role:
        name: ovirt_logout