---
- name: check connection to engine 
  become: true
  hosts: localhost
  gather_facts: false
  vars_files:
    - ovirt_auth_vars.yml
  vars:
    vm_name: b07
    storage_domain: NFS
    vm_type: server
    vm_os: 
  tasks:
    - name: Login
      ovirt_auth:
        url: "{{ url }}"
        username: "{{ username }}"
        password: "{{ password }}"


    - ovirt.ovirt.ovirt_vm_os_info:
        auth: "{{ ovirt_auth }}"
      register: result
    - ansible.builtin.debug:
        msg: "{{ result.ovirt_operating_systems }}"

    - ovirt.ovirt.ovirt_vm_os_info:
        auth: "{{ ovirt_auth }}"
        filter_keys: name,architecture
      register: result
    - ansible.builtin.debug:
        msg: "{{ result.ovirt_operating_systems }}"