---
# tasks file for create_linux_vm
    - ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"        
        state: running
        cluster: "{{ vm_cluster_default }}"
        name: "{{ vm_name }}"
        memory: 2GiB
        cpu_cores: 2
        cpu_sockets: 2
        cpu_shares: 1024
        type: "{{ vm_type }}"
        high_availability: true
        operating_system: "{{ vm_os }}"
        disks:
          - name: "{{ vm_name }}_thin_disk"
            bootable: True
        nics:
          - name: nic1