---
# tasks file for create_vm_alma_temp_and_dont_run
      - name: Creates a new Virtual Machine from template
        ovirt.ovirt.ovirt_vm:
          auth: "{{ ovirt_auth }}"
          state: present
          name: "{{ vm_name }}"
          template: "{{ vm_template_linux }}"
          cluster: "{{ vm_cluster_default }}"
